insert into ATHLETES (id, firstName, lastName, gender, country) values (1, 'Chauncey', 'Utteridge', 'Male', 'Sweden');
insert into ATHLETES (id, firstName, lastName, gender, country) values (2, 'Victoir', 'Marin', 'Male', 'Egypt');
insert into ATHLETES (id, firstName, lastName, gender, country) values (3, 'Alyce', 'Dawltrey', 'Female', 'Brazil');
insert into ATHLETES (id, firstName, lastName, gender, country) values (4, 'Brendon', 'Odeson', 'Male', 'Sweden');
insert into ATHLETES (id, firstName, lastName, gender, country) values (5, 'Mal', 'Yanov', 'Male', 'China');
insert into ATHLETES (id, firstName, lastName, gender, country) values (6, 'Katerine', 'Basketter', 'Female', 'Portugal');
insert into ATHLETES (id, firstName, lastName, gender, country) values (7, 'Milt', 'Knapton', 'Male', 'China');
insert into ATHLETES (id, firstName, lastName, gender, country) values (8, 'Jimmie', 'de Clerq', 'Polygender', 'Indonesia');
insert into ATHLETES (id, firstName, lastName, gender, country) values (9, 'Bjorn', 'Leonardi', 'Agender', 'Thailand');
insert into ATHLETES (id, firstName, lastName, gender, country) values (10, 'Angie', 'Williams', 'Male', 'China');
insert into ATHLETES (id, firstName, lastName, gender, country) values (11, 'Mahala', 'Bolitho', 'Female', 'Russia');
insert into ATHLETES (id, firstName, lastName, gender, country) values (12, 'Corabel', 'Toms', 'Female', 'Kazakhstan');
insert into ATHLETES (id, firstName, lastName, gender, country) values (13, 'Cord', 'Titford', 'Male', 'China');
insert into ATHLETES (id, firstName, lastName, gender, country) values (14, 'Alvin', 'Wigin', 'Male', 'France');
insert into ATHLETES (id, firstName, lastName, gender, country) values (15, 'Happy', 'Linneman', 'Female', 'China');
insert into ATHLETES (id, firstName, lastName, gender, country) values (16, 'Poul', 'Storres', 'Male', 'France');
insert into ATHLETES (id, firstName, lastName, gender, country) values (17, 'Albrecht', 'Husher', 'Male', 'Croatia');
insert into ATHLETES (id, firstName, lastName, gender, country) values (18, 'Ky', 'Madsen', 'Male', 'Bolivia');
insert into ATHLETES (id, firstName, lastName, gender, country) values (19, 'Kerrill', 'Sotham', 'Non-binary', 'Indonesia');
insert into ATHLETES (id, firstName, lastName, gender, country) values (20, 'Jessie', 'Mongenot', 'Female', 'Czech Republic');
insert into ATHLETES (id, firstName, lastName, gender, country) values (21, 'Wake', 'Crewes', 'Male', 'China');
insert into ATHLETES (id, firstName, lastName, gender, country) values (22, 'Morganica', 'Saull', 'Female', 'China');
insert into ATHLETES (id, firstName, lastName, gender, country) values (23, 'Kizzee', 'Beaudry', 'Female', 'China');
insert into ATHLETES (id, firstName, lastName, gender, country) values (24, 'Dinnie', 'Garrish', 'Female', 'Ireland');
insert into ATHLETES (id, firstName, lastName, gender, country) values (25, 'Dawn', 'Rieme', 'Female', 'South Africa');

INSERT INTO SPORTS (id, name, location) VALUES (1, "Basketball", "Basketball Court");
INSERT INTO SPORTS (id, name, location) VALUES (2, "Long Jump", "Track");
INSERT INTO SPORTS (id, name, location) VALUES (3, "100m Sprint", "Track");
INSERT INTO SPORTS (id, name, location) VALUES (4, "50m Butterfly", "Swimming Pool");
INSERT INTO SPORTS (id, name, location) VALUES (5, "Discus Throw", "Field");
INSERT INTO SPORTS (id, name, location) VALUES (6, "Park", "Urban Sports Park");